version: '3.7'
services:

  #PHP Service
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        - DB_HOST=db
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_DBUSER=${MYSQL_DBUSER}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
        - APP_PATH=${APP_PATH}
        - APP_ENV=${APP_ENV}
        - APP_DEBUG=${APP_DEBUG}
        - APP_KEY=${APP_KEY}
        - APP_URL=${APP_URL}
    container_name: laravel
    restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME=laravel
      - SERVICE_TAGS=dev
    working_dir: ${APP_PATH}
    volumes:
       - ./laravel/application:${APP_PATH}
       - ./laravel/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8008:80"
    volumes:
      - ./laravel/application:${APP_PATH}
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
    networks:
      - laravel-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge